# Shell
layerrule = no_anim true, match:namespace caelestia-(launcher|osd|notifications|border-exclusion|area-p>
layerrule = animation fade, match:namespace caelestia-(drawers|background>
layerrule = order 1, match:namespace caelestia-border-exclusion
layerrule = order 2, match:namespace caelestia-bar
layerrule = xray 1, match:namespace caelestia-(border|launcher|bar|sidebar|navbar|mediadisplay|sc>
layerrule = blur true, match:namespace caelestia-.*
layerrule = blur true, match:namespace qs-.*
layerrule = ignore_alpha 0.57, match:namespace caelestia-.*
